#!/bin/env make
# 
# created by awvwgk in March 2018 (v 2.0)
# this Makefile is aimed at FORTRAN code!
#
##############################################################################
## this is a generic minimal sublevel Makefile                              ##
##############################################################################

###------------------------------------------------------------------------###
# specifiy where you are in the source tree
MAINDIR := ..
# here resides the build system
MAKEDIR := $(MAINDIR)/MAKE

# set the source by hand
SRCDIR  := .

##############################################################################
## please edit this Files only:
include $(MAKEDIR)/NAME.objs
include $(MAKEDIR)/Makeconfig
## here you can give optional configurations independent from Makeconfig
-include $(MAKEDIR)/NAME.config
##############################################################################

include $(MAKEDIR)/Makerules

